---
title: "numeric eda"
author: "Hongjie Liu"
output: github_document
---

## import data

```{r}
library(tidyverse)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>% #all date mm/dd to mm/01
  select(name, id, everything())
```


## `group_by()`

```{r}
weather_df %>% 
  group_by(name, month) # output: groups: name, month [36]
```


## `summarize()`

group and then summarize.

```{r}
weather_df %>% 
  group_by(name) %>% 
  summarize(
    n_obs = n() # create a variable n_obs counting numbers of each group
  )
```

```{r}
weather_df %>% 
  count(name)
```

don't use `table()`

```{r}
weather_df %>% 
  pull(month) %>% 
  table() # cannot create a new dataframe
```

you can have multiple summaries

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize( # you can have more columns
    n_obs = n(),
    n_dist = n_distinct(date)
  )
```


## a brief aside on 2x2 tables

```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  group_by(name, cold) %>% 
  summarize(
    n_obs = n()
  ) %>% 
  pivot_wider(
    names_from = cold,
    values_from = n_obs
  )
```

or use the powerful `janitor` package

```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ "" # in case missing values
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  janitor::tabyl(name, cold)
```


## General summaries

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE), # remove missing values
    sd_prcp = sd(prcp),
    median_tmax = median(tmax, na.rm = TRUE)
  ) %>% 
  view # very good way to show a dataframe without assigning
```

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(across(prcp:tmin, mean))
```

this is a dataframe

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_path()
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) %>% 
  knitr::kable(digit = 2) # get a formatted table
```


## Grouped mutates

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax
  ) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
  geom_point()
```

lagged observations

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    yesterday_tmax = lag(tmax),
    tmax_change = tmax - yesterday_tmax
  ) %>% 
  summarize(
    sd_tmax = sd(tmax_change, na.rm = TRUE)
  )
```


One other window function

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  mutate(
    tmax_rank = min_rank(tmax) # desc(tmax) for reverse
  ) %>% 
  filter(tmax_rank < 4) %>% # 3 coldest days in a month
  arrange(name, month, tmax_rank)
```